### ISSUE TITLE
[Question] A few days ago, I traveled to Europe and intentionally opened this app, hoping to increase communication with the locals, but it was  completely unable to be used properly

### ISSUE THREAD

**Issue by zhl111** [niedev/RTranslator#83] opened 2024-10-18 06:28 UTC
The question is written in English (I can translate what you say, but questions written in English are easier to read for the other users).

Write here the question.
After I said one sentence, the microphone turned gray and couldn't be used anymore. I don't understand why, my phone is Samsung S23 Ultra.

**Comment by niedev** [comment] 2024-10-18 12:01
Hi, thank you for reporting a bug, normally in WalkieTalkie mode the microphone turns gray (and deactivates) while the app performs voice recognition and translation, in this case the microphone most likely remained gray because the translation went in a loop, as in [this issue](https://github.com/niedev/RTranslator/issues/81).
Can you confirm that the microphone was green and after speaking it turned gray?

**Comment by zhl111** [comment] 2024-10-22 14:14
Yes, I am very sure

**Comment by niedev** [comment] 2024-10-26 19:14
Ok, I'll try to solve the problem next week (I started a new job so I don't have much time, but I should be able to at least implement some fixes).

**Comment by niedev** [comment] 2024-11-01 14:38
Even though the problem is not completely solved I made a [new release](https://github.com/niedev/RTranslator/releases/tag/2.1.2) that should mitigate it enough (reducing the occurrence of this bug and stopping it early when it occurs), let me know how the app goes now 🚀.
Also, since this bug is the same as the one in issue #81 I will close this issue and leave that one open, if you have other problems about it write them there.

**Closed as completed by niedev** 2024-11-01 14:38 UTC
Labels: bug
