### ISSUE TITLE
tts initialization failed

### ISSUE THREAD

**Issue by khimaros** [niedev/RTranslator#8] opened 2024-06-19 04:44 UTC
this is on CalyxOS with eSpeak as the configured TTS engine. let me know if i can provide any other information

**Comment by the4anoni** [comment] 2024-06-19 05:31
I have same issue on LineageOS 21 with RHvoice installed and set up properly. Other apps can use RHvoice properly.

**Comment by zanovis** [comment] 2024-06-19 05:55
Same issue on GrapheneOS, Pixel 6a

**Comment by niedev** [comment] 2024-06-19 07:32
@zanovis which tts engine is giving you problems?

**Comment by niedev** [comment] 2024-06-19 07:33
I will investigate the compatibility with all the TTS cited here.

**Comment by basings** [comment] 2024-06-19 11:06
Same for me on GrapheneOS with installed google TTS from play store.

**Comment by niedev** [comment] 2024-06-19 11:58
@basings go to the RTranslator settings -> Text to speech and click on it, if the preferred engine is not the Google one, select it, if it is Google's TTS try to reinstall it, I had the same issue in the past and reinstall solved the problem, let me know if it works.

**Comment by basings** [comment] 2024-06-19 12:12
@niedev unfoortunately no success after reinstalling. I can't get into the settings. Right after model download it errors. 

![Screenshot_20240619-141226](https://github.com/niedev/RTranslator/assets/92867705/167f07a9-184e-4ced-a539-ab0a5e0d7ab0)

**Comment by niedev** [comment] 2024-06-19 12:27
Right 😅, I definitely need to move the error reporting to WalkieTalkie and Conversation modes only and make some adjustments.
For now you can access the setting directly from the settings of the phone (the setting in my app is just a link to that setting), to find the tts settings try to search "Text-to-speech" (in my phone is in Accessibility, but the location can vary, so the search is better), from there you can choose Google TTS as TTS Engine.

**Comment by basings** [comment] 2024-06-19 12:33
Unfortunately no success either
![Screenshot_20240619-143347](https://github.com/niedev/RTranslator/assets/92867705/d9d6bcd1-4c10-48eb-a9eb-524994d55698)

**Comment by niedev** [comment] 2024-06-19 12:55
Ok, so maybe it's a compatibility issue with that Custom ROM.

These days I'll manage the error better so that it doesn't block the rest of the use of the app, and then I'll try to solve the compatibility issues too (that will take more time), I'll update you here as soon as I have news.

**Comment by khimaros** [comment] 2024-06-19 14:34
thank you! @niedev personally i would be fine using it with TTS disabled. my use case is to follow continuously a conversation in another language . text only is sufficient.

**Comment by mintisan** [comment] 2024-06-20 02:19
same error on Xiaomi13

**Comment by Byte1122** [comment] 2024-06-20 09:43
same error on GrapheneOS. Can't use the app. Looking forward to use this app!

**Comment by niedev** [comment] 2024-06-20 09:49
I'm working right now on handling the error better so that you can at least use the app (even if without TTS), an update should be out today.

**Comment by Byte1122** [comment] 2024-06-20 12:02
> I'm working right now on handling the error better so that you can at least use the app (even if without TTS), an update should be out today.

Great! Also: please add a btc/crypto donation address. Love to donate if you keep supporting GrapheneOS and other altenative OS without or limited Google services.

**Comment by niedev** [comment] 2024-06-20 12:24
The update has been [released ](https://github.com/niedev/RTranslator/releases/tag/2.0.1)🚀, now the app should work without TTS, just click on "continue" when you display the error on the initial loading, let me know if it works properly now.

**Comment by niedev** [comment] 2024-06-20 12:34
> Great! Also: please add a btc/crypto donation address. Love to donate if you keep supporting GrapheneOS and other altenative OS without or limited Google services.

Thank you for wanting to help! I don't have a crypto wallet so for now I'll just leave PayPal, but I don't rule it out for the future.

**Comment by khimaros** [comment] 2024-06-20 13:37
it is working beautifully now. thank you!

**Comment by Byte1122** [comment] 2024-06-20 13:41
Also works great ! offline without any connection. Love it! and many thanks. Will surely donate !

**Comment by sadtler** [comment] 2024-06-21 03:29
There was an error with the tts initialization, do you want to continue without tts?

**Comment by a1649702136** [comment] 2024-06-24 14:27
First, "There was an error with the tts initialization, do you want to continue without tts?"
click "continue"
then show that "There was an error loading the files of the models for translation and speech recognition, try restarting thle app, if the problem persists then reset it."
So I can't start it.

**Comment by niedev** [comment] 2024-06-24 14:46
Sometimes there can be errors with the download of files (in the future I will improve the detection and management of these errors), for now the only way to resolve is to uninstall and reinstall the application, and make sure to keep the phone with the screen turned on and with RTranslator open during the download (the download also works in the background, but doing so minimizes the possibility of errors).

**Comment by AoThen** [comment] 2024-06-25 01:50
Or APP can set a local directory option and download these offline voice packages in advance, which can eliminate network factors.

**Comment by niedev** [comment] 2024-06-25 08:32
> Or APP can set a local directory option and download these offline voice packages in advance, which can eliminate network factors.

Someone already suggested it [here](https://github.com/niedev/RTranslator/issues/16), I added it to the list of things to do.

**Comment by kingdq** [comment] 2024-06-25 21:09
please provide  download address  of google tts engine or download link in the google store, because what i have found is "Speech Recognition and Synthesis from Google",but it doesn't  work.

**Comment by niedev** [comment] 2024-06-26 13:44
> please provide download address of google tts engine or download link in the google store, because what i have found is "Speech Recognition and Synthesis from Google",but it doesn't work.

That is the correct one, have you tried to restart the app? (by restart I mean close it from recent apps) If this doesn't work can you tell me if you use a custom ROM and which one?

**Comment by niedev** [comment] 2024-06-28 22:20
There is a [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.2) that should fix the TTS issues! 😁 Let me know if it works correctly.

**Comment by the4anoni** [comment] 2024-06-29 09:10
> There is a [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.2) that should fix the TTS issues! 😁 Let me know if it works correctly.

For me It fixed issue :)

**Comment by shafiev** [comment] 2024-06-30 12:03
problem too even with new release on reno oppo 11 ( android 14 )

**Comment by niedev** [comment] 2024-06-30 12:10
@shafiev could you tell me what the problem is exactly? And with which TTS?

**Comment by shafiev** [comment] 2024-06-30 12:19
@niedev i cannot start application at all 
permamently give this error at start 

**There was an error loading the files
of the models for translation and
speech recognition, try restarting
the app, if the problem persists then
reset it.
ΕΧΙΤ**

**Comment by niedev** [comment] 2024-06-30 12:42
Ok @shafiev, this error is not due to TTS but it happens when there was an error with the initial download, I'm working on it at the moment, but for now the only solution is to reinstall the app and re-download keeping the app always open in the foreground.

**Comment by shafiev** [comment] 2024-06-30 15:08
Unfortunately this solution doesn't work on my phone ( @niedev

**Comment by niedev** [comment] 2024-07-01 10:29
I'm sorry @shafiev, anyway today or tomorrow the update that will improve the download should be released, I'll let you know as soon as it comes out.

**Comment by niedev** [comment] 2024-07-02 12:45
@shafiev the [update ](https://github.com/niedev/RTranslator/releases) that improves the download is out! If you install it now it should give you the option to fix the problem by re-downloading only the corrupted files. Let me know how it works.

**Comment by shafiev** [comment] 2024-07-02 17:57
Now works,thank you @niedev 
Some offtop question is there possible to add another languages like in this model
https://translate.wmcloud.org/ ?

**Comment by niedev** [comment] 2024-07-04 21:11
> Now works,thank you @niedev Some offtop question is there possible to add another languages like in this model https://translate.wmcloud.org/ ?

In the future I will separate the languages supported by Whisper and the ones supported by NLLB, so for the text translation mode a lot more languages will be added.

**Closed as completed** 2024-07-04 21:11 UTC
