### ISSUE TITLE
No Google tts engine (I installed it)

### ISSUE THREAD

**Issue by beeinwind** [niedev/RTranslator#15] opened 2024-06-21 00:46 UTC
After downloaded all components ,this app said there's no google tts engine.i installed it in google play.but this app still asked me to install it.
I found google iis engine has a new name 
“Speech Recognition and Synthesis from Google”.
My phone is Samsung Galaxy f52 5g

**Comment by beeinwind** [comment] 2024-06-21 00:50
Samsung Galaxy f52 5g

**Comment by sadtler** [comment] 2024-06-21 03:26
There was an error with the tts initialization, do you want to continue without tts?

**Comment by niedev** [comment] 2024-06-21 09:33
If you press "continue" you will have the possibility of using the app but without TTS. Anyway it's strange, do you have a custom ROM on your phone?

**Comment by bradflaugher** [comment] 2024-06-24 10:24
I am using GrapheneOS and the app works wonderfully except for the tts. It would be great to support FOSS tts like RHVoice, which can be set as the default tts system-wide.

**Comment by niedev** [comment] 2024-06-24 10:50
I am aware of this and in the future (probably in RTranslator 2.1) I will expand the compatibility with different TTS (or directly integrate a TTS inside the app), when I will have updates I will post them in [this](https://github.com/niedev/RTranslator/issues/8) issue (now I close this one because it is practically a duplicate of the other one).

**Closed as completed by niedev** 2024-06-24 10:50 UTC
